baseURL: "https://anf.myst.rs/"
languageCode: "en-us"
title: "ANF Blogs"
theme: "eureka"
copyright: >
  &copy; 2021 <a href="https://github.com/ANF/">ANF</a>
description: "Test"
publishDir: "docs"
enableEmoji: true

menu:
  main:
    - name: Blogs
      url: "blog"
      weight: 1

    - name: Projects
      url: "projects"
      weight: 2

    - name: Series
      url: "series"
      weight: 3

    - name: Categories
      url: "categories"
      weight: 4
      
    - name: Tags
      url: "tags"
      weight: 5

taxonomies:
  category: categories
  series: series
  author: authors
  tag: tags
