baseURL: "https://anf.github.io/"
languageCode: "en-us"
title: "ANF Blogs"
theme: "eureka"
menu:
  main:
    - name: Blogs
      url: "blog"
      weight: 1
    - name: Projects
      url: "projects"
      weight: 2
    - name: Categories
      url: "categories"
      weight: 4
    - name: Tags
      url: "tags"
      weight: 5

taxonomies:
  category: categories
  author: authors
  tag: tags
