name: Build Site

on:
  push:
    branches:
      #- main
       - _main # main has been commented due to certain build errors.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Build Site
        uses: chabad360/hugo-actions@master
        with:
          buildPath: './docs'
